### ISSUE TITLE
关于文章中图片自动放大的问题

### ISSUE THREAD

**Issue by ZhengHaoYun** [XPoet/hexo-theme-ils#14]
非常喜欢作者的主题，简约干净却功能齐全！

但是有个疑惑，在文章中每个图片都会自动放大，这样本来一个小图片，然后自动放大，就会非常影响观感！
![image](https://user-images.githubusercontent.com/40732348/90953029-b1f5e480-e49a-11ea-9838-a0642f84d512.png)

**Comment by ZhengHaoYun** [comment]
您好，请问三天前发布的新版本中是否解决了此问题呢？因为我使用了`git pull`更新了主题后，发现文章中的 图片仍然是自动放大的呢，这样造成了一张图片可能会占满整个屏幕 的不佳体验，希望作者能够改善下！
然后建议取消搜索页面中自动跳转至ils的github主页的功能，我可以为您在其他地方打广告哦~但是搜索的时候总是莫名其妙就跳到github上来了，就非常的难受！

**Comment by XPoet** [comment]
@ZhengHaoYun 
- 第一个问题： `v2.0.1` 已解决，请下载使用最新版本。
- 第二个问题：本主题并无在搜索页面添加自动跳转的功能，具体可查看[我的网站](https://xpoet.cn/)，可能是你的 hexo 或 node.js 版本过低，在编译的时候出错引起的，也有可能是你配置不当引起的。

建议：
1. 下载最新[稳定版本](https://github.com/XPoet/hexo-theme-ils/releases)，替换掉旧版本使用。
2. 查看自己本机的 hexo 版本。（升级到 v4.2.0）
