### ISSUE TITLE
关于sidebar

### ISSUE THREAD

**Issue by 4Details** [XPoet/hexo-theme-ils#15]
请问我部署之后siderbar 的标题无法链接到对应部分是什么原因呀？
F12 可以得到链接，也可以在打开标签页然后访问到该位置，但是无法在当前页通过siderbar定位。
js报错
`Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null
    at HTMLAnchorElement.<anonymous> (toc.js:15)
(anonymous) @ toc.js:15`

**Comment by XPoet** [comment]
@4Details 收到反馈，这周末排查问题

**Comment by 4Details** [comment]
还遇到一个问题：点进文章分类之后默认显示条数是和首页的文章显示条数一致麽？如果一致，在文章分类页没有分页功能，默认就只能显示满足设置值的最新条数。请问这个是因为我设置的问题，还是一个bug呀？

**Comment by XPoet** [comment]
@4Details 经过排查，没找到你说的问题，麻烦发个截图或提供下你的网站链接

**Comment by 4Details** [comment]
> @4Details 经过排查，没找到你说的问题，麻烦发个截图或提供下你的网站链接

https://4details.github.io/2020/09/02/%E7%BA%A2%E9%BB%91%E6%A0%91%E7%90%86%E8%A7%A3/
你可以试一下上面的链接的sidebar，点击之后没有跳转到对应的子标题

**Comment by XPoet** [comment]
`v2.0.0-alpha` 版本已去除 sidebar 双栏模式，经过反复测试，暂无发现此问题，建议使用最新版本。

**Comment by HaroldHoo** [comment]
把
var target = document.getElementById(event.currentTarget.getAttribute('href').replace('#', ''));
改为：
var target = document.getElementById(decodeURI(event.currentTarget.getAttribute('href').replace('#', '')));

**Comment by HaroldHoo** [comment]
想彻底fix，需要ils主题作者兼容新版toc的urlencde。

或者，本地改一下toc.js，也可以：
./node_modules/hexo/lib/plugins/helper/toc.js
29行左右
const href = id ? `#${encodeURL(id)}` : null;
改为
const href = id ? `#${id}` : null;

**Comment by XPoet** [comment]
@HaroldHoo 收到反馈，我找时间解决一下这个问题

**Comment by XPoet** [comment]
该 bug 已修复，请使用 `v2.1.3` 及以上版本
