### ISSUE TITLE
关于文章分类页显示条目

### ISSUE THREAD

**Issue by 4Details** [XPoet/hexo-theme-ils#16]
遇到一个问题：点进文章分类之后默认显示条数是和首页的文章显示条数一致麽？如果一致，在文章分类页没有分页功能，默认就只能显示满足设置值的最新条数。请问这个是因为我设置的问题，还是一个bug呀？

**Comment by XPoet** [comment]
@4Details 该 bug 已修复，文章分类页和标签页已实现分页功能，最大显示10条，超过10条自动分页，可在**博客的配置文件**进行最大显示条数的更改。
更新下代码即可。
