### ISSUE TITLE
cnzz怎么加啊大佬，footer.ejs里面加完chrome显示可百分浏览器不显示

### ISSUE THREAD

**Issue by loadingfd** [XPoet/hexo-theme-ils#2]
还有就是不显示cnzz的图案或者文字，小白页也不会ejs

**Comment by XPoet** [comment]
> 还有就是不显示cnzz的图案或者文字，小白页也不会ejs

cnzz是什么？请描述清楚，条件允许的话，请附上截图

**Comment by loadingfd** [comment]
> > 还有就是不显示cnzz的图案或者文字，小白页也不会ejs
> 
> cnzz是什么？请描述清楚，条件允许的话，请附上截图

就是有个统计网站数据的 友盟
他提供js代码说放在body前
但我对ejs一窍不通https://www.umeng.com/

**Comment by XPoet** [comment]
@loadingfd 这个工具挺不错的，将在下个版本内置。
