### ISSUE TITLE
请教关于root的问题（不好意思 麻烦了）

### ISSUE THREAD

**Issue by syh0327** [XPoet/hexo-theme-ils#20]
[![png](https://s1.ax1x.com/2020/10/23/BEFsQH.png)](https://imgchr.com/i/BEFsQH)
[![png](https://s1.ax1x.com/2020/10/23/BEFyyd.png)](https://imgchr.com/i/BEFyyd)

**Comment by XPoet** [comment]
@syh0327 
1、root 这样写没问题；
2、直接打开本地的index.html是不行的，你要通过启动 hexo 服务，才能加载这些资源（css、js、image等）。
在 hexo 根目录下，使用命令 `hexo s -o`，成功启动后就能看到正常的界面了。
参考下我的：
![image](https://user-images.githubusercontent.com/24516169/97017751-e2342f00-1580-11eb-82bc-0346a99603be.png)

**Comment by XPoet** [comment]
看你截图，hexo根目录即为你的 `blog` 文件夹

**Comment by syh0327** [comment]
我知道本地服务是可以 但要是上传到github就不知道怎么弄了 主要是想和同学聊天和记录一下笔记（包括分享不可告人的事情）

**Comment by XPoet** [comment]
hexo 部署可参考这里 https://easyhexo.com/1-Hexo-install-and-config/1-4-deploy-hexo.html

遇到问题也随时问我
