### ISSUE TITLE
移动端浏览器中博客文章的目录显示异常

### ISSUE THREAD

**Issue by wroogle** [XPoet/hexo-theme-ils#3]
系统：Android Q
浏览器：Chrome 83.0.4103.96

问题描述：
在手机上用chrome打开博客文章时，发现目录会遮住文章，图片如下所示。上下移动文章时目录不变，始终在同一个位置。
[图片](https://cdn.jsdelivr.net/gh/wroogle/Image-Hosting/GuDong/%E5%8D%9A%E5%AE%A2%E7%9B%AE%E5%BD%95.jpg)

**Comment by XPoet** [comment]
@wroogle 感谢反馈问题，我会尽快处理。

**Comment by XPoet** [comment]
移动端适配已优化，更新一下主题文件即可，感谢关注。

**Comment by wroogle** [comment]
感谢修复，辛苦了❤
