### ISSUE TITLE
中文字符乱码问题

### ISSUE THREAD

**Issue by yltzdhbc** [XPoet/hexo-theme-ils#8]
您好博主，我非常喜欢这一款主题，但在我打算将他用在我的博客上的时候，有一些乱码的问题：
1.创建了 about 页面在md文件写入中文，在网页端显示出来的是乱码。
2. valine 评论系统的 placeholder: 关键字，填入中文，也显示乱码。

**Comment by yltzdhbc** [comment]
好吧，这个问题解决了，是我用vscode的时候默认编码为GB2312 ,一定要修改成UTF8。
共大家参考

**Comment by XPoet** [comment]
@yltzdhbc 🤝 感谢分享
